// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XmlSync.EntityFramework;

namespace XmlSync.Migrations
{
    [DbContext(typeof(XmlSyncDbContext))]
    partial class XmlSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11");

            modelBuilder.Entity("XmlSync.EntityFramework.Models.XML_INFO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CONTEUDO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DATA_CRIAÇÃO")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DATA_SINCRONIZACAO")
                        .HasColumnType("TEXT");

                    b.Property<string>("NOME_XML")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SINCRONIZADO")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("XML_INFOs");
                });
#pragma warning restore 612, 618
        }
    }
}
